version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-starter-kit
    ports:
      - '3000:3000'
    volumes:
      - .:/src/app
      - /src/app/node_modules
